### ISSUE TITLE
getting error when running entities list

### ISSUE THREAD

**Issue by mdeora** [racker/rackspace-monitoring-cli#80]
Traceback (most recent call last):
  File "/usr/local/bin/raxmon-entities-list", line 23, in <module>
    run_action(None, None, 'entities', 'list', callback)
  File "/usr/local/lib/python2.7/site-packages/raxmon_cli/common.py", line 124, in run_action
    instance = get_instance(username, api_key, api_url, auth_url, auth_token)
  File "/usr/local/lib/python2.7/site-packages/raxmon_cli/common.py", line 143, in get_instance
    instance = driver(username, api_key, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rackspace_monitoring/drivers/rackspace.py", line 173, in __init__
    self._initialize_connection_base_url(constructor_kwargs=kwargs)
  File "/usr/local/lib/python2.7/site-packages/rackspace_monitoring/drivers/rackspace.py", line 187, in _initialize_connection_base_url
    self.connection._populate_hosts_and_request_paths()
  File "/usr/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 602, in _populate_hosts_and_request_paths
    osa.authenticate()  # may throw InvalidCreds
  File "/usr/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 155, in authenticate
    return self.authenticate_2_0_with_apikey()
  File "/usr/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 240, in authenticate_2_0_with_apikey
    return self.authenticate_2_0_with_body(reqbody)
  File "/usr/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 264, in authenticate_2_0_with_body
    driver=self.driver)
libcloud.common.types.MalformedResponseError: <MalformedResponseException in None 'Malformed response'>: 'code: 405 body: {"methodNotAllowed":{"code":405}}'

**Comment by Kami** [comment]
I believe upgrading to latest version of Libcloud should resolve this.
