### ISSUE TITLE
Pypi disabled http access to the APIs - raxmon-version-check

### ISSUE THREAD

**Issue by ihavegerms** [racker/rackspace-monitoring-cli#91]
The raxmon-version-check script has the pypi url hardcoded to http. Attempting to run this 'as-is' produces the following error;

$ **raxmon-version-check**
Traceback (most recent call last):
  File "/Users/darren.carpenter/raxmon/lib/python2.7/site-packages/raxmon_cli/common.py", line 130, in run_action
    callback(instance, options, args, done)
  File "/Users/darren.carpenter/raxmon/bin/raxmon-version-check", line 35, in callback
    f = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: SSL is required

#######

Changing line 28 to https solves the issue;

[before]
 28 URL = 'http://pypi.python.org/pypi/rackspace-monitoring-cli/json'

[after]
 28 URL = 'https://pypi.python.org/pypi/rackspace-monitoring-cli/json'

-------

(raxmon) MQV2LVG8WL:bin darren.carpenter$ **raxmon-version-check**
Current version: 0.7.3
Latest version: 0.7.3

Your version is up to date!

**Comment by itzg** [comment]
If you want to submit a PR, that would be fantastic.

**Comment by ihavegerms** [comment]
I did so last night sir :) It had an option to auto-merge but I didn't know if it one of y'all were required to review it first.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by itzg** [comment]
That's strange then. I don't see a PR from you here

https://github.com/racker/rackspace-monitoring-cli/pulls
